import Link from "next/link";
import Head from "next/head";
import { Navigation } from "../components/Navigation";
import styles from "../styles/Home.module.css";
import {
  Button,
  Image,
  Grid,
  Text,
  Container,
  Row,
  Col,
} from "@nextui-org/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation />
      </header>
      <main className={styles.main}>
        <Container>
          <Row justify="center" align="center">
            <Col span={8}>
              <Grid.Container>
                <Grid md="3">
                  <Grid.Container>
                    <Grid css={{ h:"10%"}}>
                      <Text
                        h1
                        size={60}
                        css={{
                          textGradient: "45deg, $yellow600 -20%, $red600 100%",
                        }}
                        weight="bold"
                      >
                        Welcome to the Dark NFT World
                      </Text>
                    </Grid>
                    <Grid>
                      <Text size={20} color="#fff">Let's Jump into the dark world by claiming your NFT.</Text>
                      <Button>Mint</Button>
                    </Grid>
                  </Grid.Container>
                </Grid>
                <Grid>
                  <Image
                    css={{ borderRadius: "10px" }}
                    width={400}
                    height={400}
                    src="./dark.png"
                    alt="Default Image"
                    objectFit="cover"
                  />
                </Grid>
              </Grid.Container>
            </Col>
          </Row>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" href="https://mohitchandel.github.io">
          Made by Mohit
        </a>
      </footer>
    </div>
  );
}
