import Link from "next/link";
import Head from "next/head";
import { Navigation } from "../components/Navigation";
import styles from "../styles/Home.module.css";
import {
  Button,
  Image,
  Grid,
  Text,
  Container,
  Row,
  Col,
} from "@nextui-org/react";
import { useEffect, useState } from "react";
import {ethers} from "ethers";
import { contractABI, contractAddress } from "../utils/constants";

export default function Home() {
  const [totalCount, setTotalCount] = useState(0);

  const getTotalCount = async () => {
    const provider = new ethers.providers.JsonRpcProvider(
      `https://polygon-mumbai.g.alchemy.com/v2/${process.env.NEXT_PUBLIC_ALCHEMY_API_KEY}`
    );
    const contract = new ethers.Contract(
      contractAddress,
      contractABI,
      provider
    );
    const data = await contract.getTotalNumber();
    setTotalCount(coffees);
  };

  useEffect(() => {
    getTotalCount();
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navigation active={"home"} />
      </header>
      <main className={styles.main}>
        <Container>
          <Row justify="center" align="center">
            <Col span={8}>
              <Grid.Container css={{ h: "50%" }}>
                <Grid md="6" sm="12">
                  <Grid.Container>
                    <Grid>
                      <div>
                        <Text
                          h1
                          size={60}
                          css={{
                            textGradient: "45deg, $blue600 -20%, $pink600 50%",
                          }}
                          weight="bold"
                        >
                          Welcome to the Dark NFT World
                        </Text>
                      </div>
                      <div>
                        <Text css={{ mt: "15px" }} size={18} color="#fff">
                          Let's Jump into the dark world by claiming your NFT.
                          Mint your NFT before the 100 token supply hit its end.
                          Current Index{" "}
                          <span style={{ color: "#17C964" }}>{totalCount}</span>
                        </Text>
                      </div>
                      <div>
                        <Button weight={"sm"}>Mint</Button>
                      </div>
                    </Grid>
                  </Grid.Container>
                </Grid>
                <Grid md="6" sm="12">
                  <Image
                    css={{ borderRadius: "10px" }}
                    src="./dark.png"
                    alt="Default Image"
                    objectFit="cover"
                  />
                </Grid>
              </Grid.Container>
            </Col>
          </Row>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a target="_blank" href="https://mohitchandel.github.io">
          Made by Mohit
        </a>
      </footer>
    </div>
  );
}
